import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
from sklearn.metrics import mean_absolute_error, mean_squared_error
import os

def read_prediction_data(file_path):
    """Read prediction data from the CSV files generated by the SchNet model"""
    try:
        data = pd.read_csv(file_path)
        print(f"Successfully loaded {len(data)} records from {file_path}")
        return data
    except Exception as e:
        print(f"Error reading file {file_path}: {str(e)}")
        return None

def calc_metrics(y_true, y_pred):
    """Calculate R-squared, MAE, and RMSE"""
    # R-squared
    slope, intercept, r_value, p_value, std_err = stats.linregress(y_true, y_pred)
    r_squared = r_value**2
    
    # MAE
    mae = mean_absolute_error(y_true, y_pred)
    
    # RMSE
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    
    return r_squared, mae, rmse, slope, intercept

def plot_correlation(data, dataset_info, property_name):
    """Create and save a correlation plot with customized styling"""
    dataset_name = dataset_info['name']
    color = dataset_info['color']
    marker = dataset_info['marker']
    suffix = dataset_info['suffix']
    
    print(f"Creating plot for {dataset_name} dataset...")
    
    # Create figure
    plt.figure(figsize=(6, 5))
    ax = plt.gca()
    
    # Get data
    x = data['Target']  # DFT values (ground truth)
    y = data['Prediction']  # ML predicted values
    
    # Calculate metrics
    r_squared, mae, rmse, slope, intercept = calc_metrics(x, y)
    print(f"{dataset_name} metrics: R² = {r_squared:.3f}, MAE = {mae:.3f}, RMSE = {rmse:.3f}")
    
    # Scatter plot
    ax.scatter(x, y, alpha=0.5, color=color, marker=marker)
    
    # Add diagonal line (perfect correlation)
    min_val = min(min(x)-10, min(y)-10)
    max_val = max(max(x)+10, max(y)+10)
    ax.plot([min_val, max_val], [min_val, max_val], 'r-', alpha=0.8)
    
    # Linear regression line
    x_range = np.linspace(min(x), max(x), 100)
    y_pred = slope * x_range + intercept
    ax.plot(x_range, y_pred, '--', color='black')
    
    # Add metrics to plot
    ax.text(0.05, 0.90, f'R$^2$ = {r_squared:.3f}', transform=ax.transAxes, fontsize=18)
    ax.text(0.05, 0.82, f'MAE = {mae:.3f}', transform=ax.transAxes, fontsize=18)
    ax.text(0.05, 0.74, f'RMSE = {rmse:.3f}', transform=ax.transAxes, fontsize=18)
    
    # Add labels and title
    ax.set_xlabel(r'$\sigma_{iso}^{DFT}$ / ppm', fontsize=18)
    ax.set_ylabel(r'$\sigma_{iso}^{ML}$ / ppm', fontsize=18)
    
    # Set axis limits - check if we need to adjust based on actual data range
    data_min = min(min(x), min(y))
    data_max = max(max(x), max(y))
    
    # Use default range (-10, 70) unless data exceeds this range
    x_min = min(-10, data_min - 5)
    x_max = max(70, data_max + 5)
    y_min = x_min
    y_max = x_max
    
    ax.set_xlim(x_min, x_max)
    ax.set_ylim(y_min, y_max)
    
    # Format tick labels
    ax.tick_params(axis='both', which='major', labelsize=14, length=6, width=1)
       
    # Save plot with new naming convention
    output_filename = f'figure_X-{suffix}.png'
    plt.tight_layout()
    plt.savefig(output_filename, dpi=300)
    print(f"Saved plot to {output_filename}")
    
    # Return metrics for summary
    return {
        'Dataset': dataset_name.capitalize(),
        'R-squared': r_squared,
        'MAE': mae,
        'RMSE': rmse,
        'Samples': len(data),
        'Figure': f'figure_X-{suffix}.png'
    }

def create_summary_table(metrics_list, property_name):
    """Create a summary table of metrics and save to CSV"""
    summary_df = pd.DataFrame(metrics_list)
    
    # Save to CSV
    output_filename = f'figure_X_metrics.csv'
    summary_df.to_csv(output_filename, index=False)
    print(f"Saved metrics summary to {output_filename}")
    
    return summary_df

def main():
    print("Starting customized plotting script...")
    
    # Define dataset properties with new suffixes
    datasets = [
        {'name': 'training', 'color': 'blue', 'marker': 'o', 'suffix': 'a'},
        {'name': 'validation', 'color': 'green', 'marker': 'x', 'suffix': 'b'},
        {'name': 'testing', 'color': 'darkorange', 'marker': 's', 'suffix': 'c'}
    ]
    
    # Process each property
    properties = ['sigma_iso']  # Add more properties if needed
    
    for property_name in properties:
        print(f"\nProcessing {property_name} property...")
        metrics_list = []
        
        for dataset in datasets:
            # Define input file path with fixed "X" in the filename
            input_file = f"figure_X-{dataset['suffix']}_data.csv"
            
            # Check if file exists
            if not os.path.exists(input_file):
                print(f"Warning: File {input_file} not found. Skipping {dataset['name']} dataset.")
                continue
            
            # Read data
            data = read_prediction_data(input_file)
            if data is None:
                continue
            
            # Create plot and collect metrics
            metrics = plot_correlation(
                data,
                dataset,
                property_name
            )
            metrics_list.append(metrics)
        
        # Create summary table
        if metrics_list:
            summary_df = create_summary_table(metrics_list, property_name)
            print(f"\nSummary for {property_name}:")
            print(summary_df)
        else:
            print(f"No data was processed for {property_name}.")
    
    print("\nCustomized plotting completed successfully!")

if __name__ == "__main__":
    main()
